fix error in test #1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,4 +31,4 @@ jobs:
         region: 'europe-west1'
 
     - name: 'Test #1'
-      run: 'echo "This should fail (no token)"; "curl "${{ steps.deploy.outputs.url }}" || true'
+      run: 'echo "This curl should fail (no token)"; "curl" "${{ steps.deploy.outputs.url }}" || true'
